return {
 {threshold=0,name='Basic Reactor',color=Color3.fromRGB(40,207,255)},
 {threshold=10000,name='Ringed Reactor',color=Color3.fromRGB(55,229,244)},
 {threshold=1000000,name='Fusion Reactor',color=Color3.fromRGB(135,245,223)},
 {threshold=100000000,name='Quantum Reactor',color=Color3.fromRGB(119,175,255)},
 {threshold=10000000000,name='Singularity Reactor',color=Color3.fromRGB(255,196,112)},
}
