return {
 {id='cranks',name='Reinforced Cranks',requires='crank',count=10,cost=300,target='crank',mult=2,effect='Hand Crank ×2'},
 {id='wiring',name='Improved Wiring',requires='battery',count=15,cost=20000,target='all',mult=2,effect='All production ×2'},
 {id='cooling',name='Efficient Cooling',requires='diesel',count=15,cost=150000,target='generators',mult=1.5,effect='All generators ×1.5'},
 {id='overclock',name='Overclocking',requires='nuclear',count=10,cost=300000,target='nuclear',mult=2,effect='Nuclear Reactor ×2'},
 {id='containment',name='Fusion Containment',requires='fusion',count=1,cost=750000,target='fusion',mult=2,effect='Fusion Core ×2'},
 {id='physics',name='Experimental Physics',requires='quantum',count=1,cost=25000000,target='quantum',mult=3,effect='Quantum Reactor ×3'},
 {id='artsing',name='Artificial Singularity',requires='singularity',count=1,cost=1000000000,target='all',mult=2,effect='All production ×2'},
}
