"""layout.json -> src/ServerStorage/BuildTools/CrystalCavernsLayout.luau (compact data, read by BuildCrystalCaverns).
O = each mesh's bbox-centre offset from its Blender origin, already in Roblox mesh space (FBX export maps Blender
(x, y, z) -> Roblox mesh (-x, z, y)); the build adds 180 degrees of yaw because the cave runs toward -Z in Studio
(world (x, y, z) -> (x, z, EntranceZ - y)).
items = { asset, glow colour or false, x, y, z, rot, scale, sx }   (y = studs into the cave, z = up, rot = degrees)
Run:  python layout_to_luau.py"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "../../src/ServerStorage/BuildTools/CrystalCavernsLayout.luau"))
L = json.load(open(os.path.join(HERE, "layout.json")))
KB = json.load(open(os.path.join(HERE, "kit_bounds.json")))
# original props (build_models.py), bounds relative to each object's origin (Blender, Z-up)
KB.update({
    "QuartzWallA": {"min": [-30, -6.6, -.4], "max": [30, 6.6, 40]},
    "QuartzWallB": {"min": [-30, -6.7, -.4], "max": [30, 6.6, 40]},
    "QuartzWallC": {"min": [-30, -6.7, -.5], "max": [30, 6.6, 40]},
    "CrystalCluster1": {"min": [-3, -2.2, -.7], "max": [2.8, 2.3, 9]},
    "CrystalCluster2": {"min": [-4, -3.7, -1], "max": [3.8, 2.8, 12.9]},
    "CrystalCluster3": {"min": [-2.9, -2.8, -.8], "max": [3, 2.6, 6]},
    "CrystalCluster4": {"min": [-3.8, -5.6, -.8], "max": [6, 3.7, 14.8]},
    "Boulder1": {"min": [-4.9, -4, -.7], "max": [4.9, 4.3, 6]},
    "Boulder2": {"min": [-6.6, -5.3, -.8], "max": [6.8, 5.7, 8.6]},
    "CeilingCrack": {"min": [-22.7, -14.3, -4], "max": [22.8, 14.1, 2]},
})


def n(v, d=1):
    s = ("%." + str(d) + "f") % v
    s = s.rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def offset(a):
    lo, hi = KB[a]["min"], KB[a]["max"]
    return (-(lo[0] + hi[0]) / 2, (lo[2] + hi[2]) / 2, (lo[1] + hi[1]) / 2)


used = sorted({it["asset"] for it in L["items"] if it["kind"] not in ("light", "shaft", "marker")})
out = ["-- GENERATED by assets/crystal-caverns/layout_to_luau.py from layout.json. Do not edit by hand.",
       "-- items: { asset, glow colour or false, x, y (into the cave), z (up), rot (deg), scale, sx }; O: mesh centre offsets",
       "return {",
       f"\tW = {L['W']}, D = {L['D']}, H = {L['H']}, NestY = {n(L['NEST_Y'])}, Gap = {L['GAP']},",
       "\twalls = { " + ", ".join(f"{{ y = {w['y']}, x0 = {n(w['x0'])}, x1 = {n(w['x1'])} }}" for w in L["walls"]) + " },",
       "\tcracks = { " + ", ".join(n(it["y"]) for it in L["items"] if it["asset"] == "CeilingCrack") + " },",
       "\tO = {"]
for a in used:
    out.append(f"\t\t{a} = {{ {', '.join(n(v, 2) for v in offset(a))} }},")
out.append("\t},")
out.append("\tlights = { " + ", ".join(f'{{ {n(i["x"])}, {n(i["y"])}, {n(i["z"])}, "{i["color"]}", {n(i["range"])}, {n(i["brightness"])} }}'
                                       for i in L["items"] if i["kind"] == "light") + " },")
out.append("\tshafts = { " + ", ".join(f'{{ {n(i["x"])}, {n(i["y"])}, {n(i["z"])}, {n(i["height"])}, {n(i["width"])} }}'
                                       for i in L["items"] if i["kind"] == "shaft") + " },")
out.append("\titems = {")
row = []
for it in L["items"]:
    if it["kind"] in ("light", "shaft", "marker"):
        continue
    glow = f'"{it["color"]}"' if it["kind"] == "glow" else "false"
    f = [f'"{it["asset"]}"', glow, n(it["x"]), n(it["y"]), n(it["z"]), n(it.get("rot", 0)), n(it.get("scale", 1), 2)]
    if it.get("sx"):
        f.append(n(it["sx"], 3))
    row.append("{" + ",".join(f) + "}")
    if len(row) == 4:
        out.append("\t\t" + ", ".join(row) + ",")
        row = []
if row:
    out.append("\t\t" + ", ".join(row) + ",")
out += ["\t},", "}", ""]
open(OUT, "w", newline="\n").write("\n".join(out))
print("wrote", OUT, os.path.getsize(OUT), "bytes")
